### ISSUE TITLE
Cvars for l4d2_cs_ladders

### ISSUE THREAD

**Issue by nikita1824** [LuxLuma/L4D-small-plugins#1]
It's just a suggestion for l4d2_cs_ladders. Can you add cvars to be able to toggle ability to use melee weapons on ladders? SI are able to use claw weapons due to this. Thank you for your attention.

**Comment by LuxLuma** [comment]
Ill look about doing it, This will likely create another dependency using DHooks detours fork.
https://forums.alliedmods.net/showpost.php?p=2737209 is more geared towards these actions.
